export const UPDATE_NAV = 'UPDATE_NAV';
export const UPDATE_PAGES = 'UPDATE_PAGES';
export const UPDATE_PAGE_SELECTED = 'UPDATE_PAGE_SELECTED';
export const UPDATE_COMPONENT_ORDER = 'UPDATE_COMPONENT_ORDER';
export const UPDATE_COMPONENT_CONTENT = 'UPDATE_COMPONENT_CONTENT';
export const UPDATE_PAGE_COMPONENT = 'UPDATE_PAGE_COMPONENT';
export const SAVE_CHANGES = 'SAVE_CHANGES';
